### PR TITLE
Merged windows branch to github branch

### PR DESCRIPTION
**Pull request by horttanainen**

### CODE REVIEW

**Review by mheiskan — CHANGES_REQUESTED** [review]
There seem to be several minor interoperability issues which we might just as well resolve in this merge.

#define _USE_MATH_FILES should be avoided as a legacy construct. The use of M_PI should be replaced with boost math constants.

CMakeLists.txt REMOVE_ITEM should be conditional on the platform being Windows. However, not having tried the cmake files in Linux yet, there might be much more serious issues to resolve first.

#include <math.h> in AstronomyLunarPhase.cpp should be replaced with #include <cmath>

boost includes in the same file should use <> instead of ""

boost::regex_match ifdef might be unnecessary in DirectoryMonitor.cpp, better try using the version working in Windows in Linux as well.

std::size_t and std::time_t specific to_string methods might work as is in Linux too - we'll just have to test it.

Using #include <stdint.h> in Linux should be replaced by <cstdint>, and interoperability should be checked again.

**Comment by mheiskan** [comment]
Pushed a modified version that works in Linux. Please test if it works fine in Windows as well.

**Comment by horttanainen** [comment]
I'll be testing this out tomorrow. Thanks for solving the MATH_DEFINES nightmare.

**Comment by horttanainen** [comment]
It seems to work just fine.

**Pull request merged**
